[package]
name = "tx-manager"
license = "Apache-2.0"
version = "0.3.1"
homepage = "https://cartesi.io"
edition = "2021"
authors = [
  "Renan Santos <renan.santos@cartesi.io>",
  "Gabriel Coutinho de Paula <gabriel.coutinho@cartesi.io>"
]

[dependencies]
ethers = { version = "0.17", features = ["rustls"] }
tokio = { version = "1", features = ["fs", "macros"] }
serde = "1.0"
serde_json = "1.0"
async-trait = "0.1"
async-recursion = "1.0"
reqwest = { version = "0.11", features = ["json"] }
snafu = "0.7"
structopt = "0.3"
tracing = "0.1"
thiserror = "1.0"
url = "2.2"

[dev-dependencies]
tracing-subscriber = "0.3"
serial_test = "0.8"
matches = "0.1"
